### ISSUE TITLE
Door but cannot navigate

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#279] opened 2018-01-08 15:52 UTC
## Would you like to work on this
No
![image](https://user-images.githubusercontent.com/14032427/34678762-114541ca-f4ba-11e7-8c7b-6d407972a234.png)

**Comment by brain-sick** [comment] 2018-01-08 19:25
i have also noticed this issue and i wan't to work on this. Assign this to me

**Comment by niccokunzmann** [comment] 2018-01-08 19:29
@brain-sick You can work on it, then. Please share your progress.

**Comment by brain-sick** [comment] 2018-01-09 08:48
i got the issue and the fix, but i wan't some clarity about gameplay, is it nessecary that we must get the key before we find the treasure

**Comment by brain-sick** [comment] 2018-01-09 09:05
i fixed the bug, what i did is that , when ever we get the key then only we can enter the treasure and the only door to enter the treasure was from left, that is from the cricket ground side.
Please tell me how to commit the changes.

**Comment by niccokunzmann** [comment] 2018-01-09 12:19
@brain-sick Please ask in the chat how to create a pull request. What do you try to do? There is also documentation in the readme file, if I remember correctly.

**Comment by brain-sick** [comment] 2018-01-09 12:26
i discovered the issue is already solved in the new clone i did

**Comment by brain-sick** [comment] 2018-01-09 12:27
it was not passing through the door just because the played didn,t had the key to move to the treasure tile, i think this is not an issue

**Comment by abishekvashok** [comment] 2018-01-09 15:38
@brain-sick pls implement a behavior where the door tile maybe rendered (used) when we have the key and the current tile that's there (wall) when we don't have a key. It will improve the game, won't it?

**Comment by niccokunzmann** [comment] 2018-01-14 10:09
Current state:
- The treasure tile can not be entered from the left.
- The key tile can be left to the top

Fixes:
- treasure tile: Allow entering from the left, leaving to the left
- key tile: do not allow leaving to the top and entering from the top: make the wall a wall.

**Comment by brain-sick** [comment] 2018-01-14 10:29
the game isn,t even running, how shall i test it

**Comment by niccokunzmann** [comment] 2018-01-14 13:01
@brain-sick If the game does not work, please open an issue and describe what you can see.

**Comment by brain-sick** [comment] 2018-01-14 17:58
ok i got it i will do it.

**Closed** 2018-01-18 12:04 UTC
Labels: bug, help wanted
