### ISSUE TITLE
Add a suitable icon for labyrinth

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#392] opened 2018-01-11 06:21 UTC
### Expected results
Add suitable icon for labyrinth like following
![labyrinthicon](https://user-images.githubusercontent.com/33794760/34811187-a26c4e02-f6c5-11e7-8edc-d3be4ff4e76b.png)

### Actual results
Current icon is not suitable

### Steps to reproduce the issue
Change icon

## Would you like to work on this
Yes,

**Comment by STEdirisuriya** [comment] 2018-01-11 06:22
@niccokunzmann I want places where shows icon,
Like on index.heml header, there is one of icon. Please tell me all other places

**Comment by YashKumarVerma** [comment] 2018-01-11 08:34
Duplicate of #88

**Comment by niccokunzmann** [comment] 2018-01-11 09:28
You can put this into all the other HTML files.

- index
- credits
- contributors

**Comment by niccokunzmann** [comment] 2018-01-11 09:29
@STEdirisuriya Please proceed with your updates in #88 because other people would also like to know about it.

**Closed by niccokunzmann** 2018-01-11 09:29 UTC
